[package]
name = "todosage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
indoc = "2.0.3"
lazy_static = "1.4.0"
regex = "1.9.1"
walkdir = "2.3.3"
