import { nodeResolve } from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import { base64 } from "rollup-plugin-base64";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

function writeManifest() {
  const fs = require("fs");
  const toml = require("@iarna/toml");

  // read the Cargo.toml file
  const cargo = toml.parse(fs.readFileSync("./Cargo.toml", "utf-8"));

  // write the manifest.json file
  fs.writeFileSync(
    "./dist/manifest.json",
    JSON.stringify({
      id: cargo.package.name,
      name: cargo.package.name,
      version: cargo.package.version,
      description: cargo.package.description ?? "",
      author: "Isaac Ruben",
      license: cargo.package.license ?? "",
      isDesktopOnly: false,
    })
  );
}

export default {
  input: "src/index.js",
  output: {
    file: "dist/main.js",
    sourcemap: "inline",
    format: "cjs",
    exports: "default",
    banner,
  },
  external: ["obsidian"],
  plugins: [
    nodeResolve({ browser: true }),
    commonjs(),
    base64({ include: "**/*.wasm" }),
    {
      name: "manifest-writer",
      writeBundle() {
        writeManifest();
      },
    },
  ],
};
